const foods = [
  {
    cuisine: "Japanese",
    dishes: [
      "Sushi",
      "Udon",
      "Tofu",
      "Tempura",
      "Yakitori",
      "Sashimi",
      "Ramen",
      "Donburi",
      "Natto",
      "Oden",
      "Tamagoyaki",
      "Soba",
      "Tonkatsu",
      "Kashipan",
      "Sukiyaki",
      "Miso Soup",
      "Okonomiyaki",
      "Mentaiko",
      "Nikujaga",
      "Curry Rice",
      "Unagi no Kabayaki",
      "Shabu Shabu",
      "Onigiri",
      "Gyoza",
      "Takoyaki",
      "Kaiseki Ryori",
      "Edamame",
      "Yakisoba",
    ],
  },
  {
    cuisine: "American",
    dishes: [
      "Hamburger",
      "Key lime pie",
      "Tater tots",
      "Cobb salad",
      "Pot roast",
      "Banana split",
      "Cornbread",
      "Biscuits 'n' gravy",
      "Smithfield ham",
      "Chicken fried steak",
      "Meatloaf",
      "Grits",
      "Macaroni and cheese",
      "Crabcakes",
      "Peanut butter sandwich",
      "Fried chicken and waffles",
      "Clam chowder",
      "Lobster rolls",
      "Buffalo wings",
      "Barbecue ribs",
      "Apple pie",
      "Philly cheese steak",
      "Hot dogs",
      "Cheeseburger",
    ],
  },
  {
    cuisine: "Chinese",
    dishes: [
      "Hotpot",
      "Braised pork",
      "Braised pork belly",
      "Dumplings",
      "Stir-fried Noodles",
      "Peking Roasted Duck",
      "Fried Rice",
      "Sweet and sour pork",
      "Char siu",
      "Century egg",
      "Kung Pao chicken",
      "Buddha's delight",
      "Baozi",
      "Dim Sum",
      "Potsticker",
      "Xiaolongbao",
      "Zongzi",
      "Mooncake",
      "Congee",
    ],
  },
  {
    cuisine: "Indian",
    dishes: [
      "Curry",
      "Butter chicken",
      "Chicken tikka masala",
      "Fish curry",
      "Kebab",
      "Korma",
      "Biryani",
      "Kofta",
      "Pakora",
      "Dal makhani",
      "Crisp papadum",
      "Naan",
      "Palak paneer",
    ],
  },
  {
    cuisine: "Italian",
    dishes: [
      "Pasta",
      "Pizza",
      "Bottarga",
      "Lasagna",
      "Steak",
      "Ribollita",
      "Polenta",
      "Ossobuco",
      "Risotto",
      "Carbonara",
      "Truffles",
      "Focaccia",
      "Arancini",
      "Gelato",
      "Tiramisu",
    ],
  },
  {
    cuisine: "Mexican",
    dishes: [
      "Tacos",
      "Chilaquiles",
      "Pozole",
      "Tostadas",
      "Chiles en nogada",
      "Elote",
      "Enchiladas",
      "Guacamole",
      "Tamales",
      "Burrito",
      "Chimichangas",
      "Lentil soup",
      "Fajitas",
      "Quesadillas",
      "Nachos",
    ],
  },
  {
    cuisine: "Thai",
    dishes: [
      "Chicken Satay",
      "Tom Yam Soup",
      "Pad Thai",
      "Chicken Curry",
      "Som Tam (Papaya Salad)",
      "Fish Curry",
      "Massaman Curry",
    ],
  },
  {
    cuisine: "French",
    dishes: [
      "Baguette",
      "Brioche",
      "Cassoulet",
      "Crème Brûlée",
      "Crêpe",
      "Croissant",
      "Escargot",
      "Galette Complète",
      "Macaron",
      "Omelette",
      "Quiche",
      "Ratatouille",
      "Soufflé",
      "Steak Tartare",
      "Tarte",
      "Tartine",
    ],
  },
  {
    cuisine: "Vietnamese",
    dishes: ["Pho", "Banh Mi", "Bun Cha"],
  },
];

export const cuisines = [
  "Japanese", "American", "Chinese", "Indian", "Italian", "Mexican", "Thai", "French", "Vietnamese"
];
export default foods;
