const foods = [
  {
    cuisine: "japanese",
    dishes: [
      "sushi",
      "udon",
      "tofu",
      "tempura",
      "yakitori",
      "sashimi",
      "ramen",
      "donburi",
      "natto",
      "oden",
      "tamagoyaki",
      "soba",
      "tonkatsu",
      "kashipan",
      "sukiyaki",
      "miso soup",
      "okonomiyaki",
      "mentaiko",
      "nikujaga",
      "curry rice",
      "unagi no kabayaki",
      "shabu shabu",
      "onigiri",
      "gyoza",
      "takoyaki",
      "kaiseki ryori",
      "edamame",
      "yakisoba",
    ],
  },
  {
    cuisine: "american",
    dishes: [
      "hamburger",
      "key lime pie",
      "tater tots",
      "cobb salad",
      "pot roast",
      "banana split",
      "cornbread",
      "biscuits 'n' gravy",
      "smithfield ham",
      "chicken fried steak",
      "meatloaf",
      "grits",
      "macaroni and cheese",
      "crabcakes",
      "peanut butter sandwich",
      "fried chicken and waffles",
      "clam chowder",
      "lobster rolls",
      "buffalo wings",
      "barbecue ribs",
      "apple pie",
      "philly cheese steak",
      "hot dogs",
      "cheeseburger",
    ],
  },
  {
    cuisine: "chinese",
    dishes: [
      "hotpot",
      "braised pork",
      "braised pork belly",
      "dumplings",
      "stir-fried noodles",
      "peking roasted duck",
      "fried rice",
      "sweet and sour pork",
      "char siu",
      "century egg",
      "kung pao chicken",
      "buddha's delight",
      "baozi",
      "dim sum",
      "potsticker",
      "xiaolongbao",
      "zongzi",
      "mooncake",
      "congee",
    ],
  },
  {
    cuisine: "indian",
    dishes: [
      "curry",
      "butter chicken",
      "chicken tikka masala",
      "fish curry",
      "kebab",
      "korma",
      "biryani",
      "kofta",
      "pakora",
      "dal makhani",
      "crisp papadum",
      "naan",
      "palak paneer",
    ],
  },
  {
    cuisine: "italian",
    dishes: [
      "pasta",
      "pizza",
      "bottarga",
      "lasagna",
      "steak",
      "ribollita",
      "polenta",
      "ossobuco",
      "risotto",
      "carbonara",
      "truffles",
      "focaccia",
      "arancini",
      "gelato",
      "tiramisu",
    ],
  },
  {
    cuisine: "mexican",
    dishes: [
      "tacos",
      "chilaquiles",
      "pozole",
      "tostadas",
      "chiles en nogada",
      "elote",
      "enchiladas",
      "guacamole",
      "tamales",
      "burrito",
      "chimichangas",
      "lentil soup",
      "fajitas",
      "quesadillas",
      "nachos",
    ],
  },
  {
    cuisine: "british",
    dishes: [
      "the full english",
      "black pudding",
      "fish and chips",
      "sausage roll",
      "eton mess",
      "scones",
      "shepherd's pie",
      "beef wellington",
      "afternoon tea",
      "cornish pasty"
    ],
  },
  {
    cuisine: "french",
    dishes: [
      "baguette",
      "brioche",
      "cassoulet",
      "crème brûlée",
      "crêpe",
      "croissant",
      "escargot",
      "galette complète",
      "macaron",
      "omelette",
      "quiche",
      "ratatouille",
      "soufflé",
      "steak tartare",
      "tarte",
      "tartine",
    ],
  },
  {
    cuisine: "mediterranean",
    dishes: [
      "pita",
      "greek salad",
      "baklava",
      "borek",
      "mezze",
      "fattoush salad",
      "falafel",
      "shakshuka",
      "couscous",
      "ratatouille",
      "paella",
      "tapas",
      "soufflé",
      "pizza margherita",
      "wine",
    ],
  },
  
];

export const cuisines = [
  "japanese", "american", "chinese", "indian", "italian", "mexican", "british","french", "mediterranean"
];
export default foods;
